### ISSUE TITLE
Getting "Error: Job status message must be a string" on running the Import job on Parse

### ISSUE THREAD

**Issue by droidster** [FirebaseExtended/parse-migration-tools#7]
I'm getting this error after adding Parse.Cloud.useMasterKey() in all the functions of migrator.js. Earlier I was getting the error as mentioned in #6.

```
Error: Job status message must be a string
    at updateJobMessageAndReturn (<anonymous>:1159:7)
    at Object.error (<anonymous>:1221:9)
    at migrator.js:337:21
    at f (Parse.js:3:9004)
    at Parse.js:3:8496
    at Array.forEach (native)
    at Object.x.each.x.forEach [as _arrayEach] (Parse.js:1:661)
    at c.extend.reject (Parse.js:3:8449)
    at f (Parse.js:3:9199)
    at Parse.js:3:8496
```

What should be done?

**Comment by inlined** [comment]
Looks like your migration job failed and the failure handler itself needs to convert the Error into a string. 4305a44 should fix this for you; your job is still failing but now you'll get an error message for why.
